apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  repository: https://VM-NAME-1:8879/

charts:
- name: db-secret-argo
  source:
    repository: $(repository)

- name: db-secret-decapod-db
  source:
    repository: $(repository)

- name: postgresql
  source:
    repository: $(repository)

- name: argo-workflows
  source:
    repository: $(repository)
